### ISSUE TITLE
Create a 404 Page

### ISSUE THREAD

**Issue by girlscript-asansol** [gsasansol/GirlScript-Asansol#15]
Changes are to be made in index.html, styles.html and index.js files.

### 404 Page should contain:
- Don't have to create the discord chat bot.
- Links: 
      - Explore our site: redirect to the home page.
      - Create hylerlinks to different home page component, refer to issue #1. 

___
### Design 
Inspo: (You can refer to it and can make your own interpretations too, Creativity is welcomed.)

![Screenshot from 2022-09-30 20-47-00](https://user-images.githubusercontent.com/104223990/193302268-467a1a94-87a4-4ee0-99cf-d75c3b0e80b8.png)

### Please join the [Discord](https://discord.com/invite/aVRPbMYfFH) to discuss design of the components.

**Comment by Subhangi0707** [comment]
I want to work on this issue under hactkoberfest 2022

**Comment by LostButton** [comment]
Hello, I would like to create your error 404 page is that ok?

**Comment by girlscript-asansol** [comment]
@LostButton Issues are assigned on 1st come, 1st serve basis. You can check the other issues in the repo.

**Comment by jay-io** [comment]
@Subhangi0707  If you would rather like to consider a less cluttered solution, you can add your html/js components in separate folders (with appropriate feature naming) inside [`components/[feature]`](https://github.com/gsasansol/GirlScript-Asansol/tree/main/components) instead of the `index.html` in the root. We'll have it merged later into the main HTML file (we'll put up a separate issue). The contents of `[feature]` can be: `index.html`, `styles.css`, `index.js` with the body of `index.html` wrapping the component.

**Comment by jay-io** [comment]
@LostButton Thank you for understanding. We're having a lot of contributors for hacktoberfest and it's only fair to go by the first-one-first rule. Good luck to you too!

**Comment by pratiksrivastava01** [comment]
@girlscript-asansol can I work on this
