### ISSUE TITLE
Addition : Issue Templates 🛠

### ISSUE THREAD

**Issue by IAmTamal** [gsasansol/GirlScript-Asansol#35]
## What i am suggesting to add ? 

I am suggesting to add **Issue Templates** to the repository, it can be as many categories as needed - primary categories of issues are mostly : `bugs`, `docs`, `general feature` and so on.

## Why to add it ? 

Adding an issue Template allows you to organize the issues made by folks in a much better way.
 - We can know if someone wants to add a feature.
 - We can know if someone wants to write a test or maybe fix something in the website
 - Here's a general idea : 
 
![image](https://user-images.githubusercontent.com/72851613/192107388-3b5564d1-4efc-4e05-8fd8-ecb271136a77.png)

## Can i work on it ? 

Yes, i will be glad to help an Opensource project grow more !

**Comment by utkarsh006** [comment]
@IAmTamal Assign me this issue.

**Comment by jay-io** [comment]
Thank you for the suggestion but maybe, we'll look into this towards the end of Hacktoberfest. For now, we want to stick to a dynamic approach because we're mentoring a very select group of beginners in webdev and we need to explain the responsibilities as elaborately as possible. Could you please open a custom issue thread in our Discord so that we can get back to you when the time comes? I'll have to close this for now.

**Comment by IAmTamal** [comment]
> 

So here's something i wanted to ask. 

Using Issue templates which technically works like a form with different types of field inside where someone can add data (texts, screenshots, markdown files) , which helps sort different types of issues like bugs, Major changes, new features and explain the roles and responsiblities involved , rather a description of that whole issue in a more detailed manner are not "dynamic" enough  for beginners to help them understand exactly what the issue is ? 

Anyways nvm, i thought beginners would  prefer something more structured. 
Have a great day.

**Comment by jay-io** [comment]
@IAmTamal Don't get me wrong. I actually wanted to assign you this because it only makes sense to have a template but I am asked to rule out such issues as unnecessary as of now for certain reasons I don't understand myself. @girlscript-asansol will assign you to this if there is a change of mind : /

![](https://y.yarn.co/66b0bd01-8563-45bd-9fcc-6ea363f59f3f_text.gif)
