### ISSUE TITLE
Migrate the past evemts section

### ISSUE THREAD

**Issue by girlscript-asansol** [gsasansol/GirlScript-Asansol#66]

**Comment by Sahilbal** [comment]
@soumali28  changes are required in index.html beacause path of img in img tag is wrong for first three images. See in the below picture  img tag should contain ".Assets/event1.png" instead of ./Assets/events2.png 
![Capture (2)](https://user-images.githubusercontent.com/114430429/193995081-93daf566-bbb3-41f9-a9e3-19bcb0f58f77.PNG)
